// Question 23: Conditional Tests: Write a series of conditional tests. Predict the results of each test.
var fruit = 'mango';
console.log('is fruit == mango? I predict True');
console.log(fruit == 'mango');
console.log('is fruit == apple? I predict False');
console.log(fruit == 'apple');
var vagetable = 'potato';
console.log('is vagetable == tomato? I predict False');
console.log(vagetable == 'tomato');
console.log('is vagetable == potato? I predict True');
console.log(vagetable == 'potato');
var dish = 'biryani';
console.log('is dish == biryani? I predict True');
console.log(dish == 'biryani');
console.log('is dish == pulao? I predict False');
console.log(dish == 'pulao');
var sweet = 'chocolate';
console.log('is sweet == chocolate? I predict True');
console.log(sweet == 'chocolate');
console.log('is sweet == candy? I predict False');
console.log(sweet == 'candy');
var cake = 'vanilla';
console.log('is cake == vanilla? I predict True');
console.log(cake == 'vanilla');
console.log('is cake == strawberry? I predict False');
console.log(cake == 'strawberry');
